### PR TITLE
Swift 5.10 Workflow

### PR DESCRIPTION
**Pull request by dimitribouniol**
Added a CI workflow for Swift 5.10.

@yim-lee If everything looks good, could you please add the CI setup for this?

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
LGTM - ready to merge once it's set up @yim-lee

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
CI for Swift 5.10 is set up and passing. 

Just want to point out that the filename deviates slightly from the others. Its extension is `.yml` rather than `.yaml`.

**Comment by dimitribouniol** [comment]
> Its extension is `.yml` rather than `.yaml`.

Good catch! I wonder if Xcode did that when I ⇧⌘S’ed to duplicate the file? I won’t be at a computer for another few hours, but I’ll poke you when I fix it, thanks!

**Comment by dimitribouniol** [comment]
Well that is an interesting Xcode bug…

https://github.com/swift-server/webauthn-swift/assets/225505/7690cbad-f8ef-462e-a324-6b3c7dfdec1e

**Comment by dimitribouniol** [comment]
@yim-lee I updated the filename if you could fix the configuration, sorry about that!

**Comment by yim-lee** [comment]
@dimitribouniol No worries. CI updated.

@swift-server-bot test this please

**Review by 0xTim — APPROVED** [review]

**Pull request merged**
