### PR TITLE
AuthenticatorData  credentialID length check as per spec

### LINKED ISSUE #39: AuthenticatorData never validates that credentialID is <= 1023 bytes
According to the [W3C Draft](https://w3c.github.io/webauthn/#sctn-attested-credential-data):
>  _**credentialIdLength**_ (2): Byte length **L** of credentialId, 16-bit unsigned big-endian integer. Value MUST be ≤ 1023.

Noticed this in passing, will probably submit a PR for it tomorrow though.

### PR DESCRIPTION
**Pull request by dimitribouniol**
Added a check per spec for the credentialID length when deserialized AuthenticatorData.

Fixes #39

### CODE REVIEW

**Review by marius-se — APPROVED** [review]
Thanks! LGTM

**Review by 0xTim — CHANGES_REQUESTED** [review]
Would it be possible to add a test to demonstrate this?

**Comment by dimitribouniol** [comment]
> Would it be possible to add a test to demonstrate this?

Good callout, added!

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by 0xTim** [comment]
This is a legitimate API breakage error and we should sort this out in a future PR. See #54 for more details

**Comment by dimitribouniol** [comment]
> This is a legitimate API breakage error and we should sort this out in a future PR. See #54 for more details

Thanks for filing the issue. As discussed in Slack a few weeks back, I’ll probably tackle it in an hour or so!

**Pull request merged**
